fix: writable page should not be frozen
nervosnetwork/ckb-vm pull request #142
Opened 2021-03-30 08:21 UTC by mohanson

2021-03-30 08:41 UTC, xxuejie requested changes
This is a breaking change, it should also only be enabled in version 1 and beyond.

2021-04-01 01:22 UTC, xxuejie reviewed
Can we add test cases to ensure the correct behavior for both version 0 and 1?

2021-04-01 02:29 UTC, mohanson commented
@xxuejie I added the tests

2021-04-01 02:53 UTC, xxuejie approved these changes

2021-04-01 02:57 UTC, merged