In int mode, support dynamic setting of memory
nervosnetwork/ckb-vm pull request #301
Opened 2022-10-26 07:52 UTC by joii2020

Add dynamic memory support to ckb-vm interpreter

2022-10-26 08:00 UTC, mohanson commented on src/machine/mod.rs
> +    pub fn set_peak_memory_usage(mut self, memory: usize) -> Self {
Assert that memory % RISCV_PAGESIZE == 0

2022-10-26 08:07 UTC, mohanson commented on src/machine/mod.rs
> +    peak_memory_usage: usize,
It is recommended to rename it to `memory_size`, `peak_memory_usage` is a concept in `spawn`.

2022-10-27 07:20 UTC, XuJiandong requested changes

2022-10-27 07:20 UTC, XuJiandong commented on src/machine/mod.rs
> +    pub fn set_peak_memory_usage(mut self, memory: usize) -> Self {
The name should be "set_memory_size"

2022-10-31 01:14 UTC, closed without merging