[WIP] Support dynamic setting of memory
nervosnetwork/ckb-vm pull request #304
Opened 2022-11-04 09:09 UTC by joii2020

Support dynamic setting of memory.
completed:interpreter, asm_x64
todo: asm_aarch64

2022-11-10 02:13 UTC, XuJiandong requested changes

2022-11-10 02:13 UTC, XuJiandong commented on definitions/src/asm.rs
> +            let machine_size =
Add some comments here.

2022-11-10 02:13 UTC, XuJiandong commented on examples/ckb-vm-runner.rs
> +    let machine_builder = machine_builder;
not needed.

2022-11-16 11:31 UTC, XuJiandong requested changes

2022-11-16 11:31 UTC, XuJiandong commented on tests/test_dy_memory.rs
> +    let buffer = fs::read("tests/programs/alloc_many").unwrap().into();
where is the source code of "alloc_many"?

2022-11-23 02:11 UTC, mohanson submitted a review, later dismissed
LGTM

2022-11-23 03:00 UTC, mohanson approved these changes

2022-11-23 03:03 UTC, merged