Fuzz isa_a with spike-ffi
nervosnetwork/ckb-vm pull request #333
Opened 2023-03-30 01:23 UTC by mohanson

- Implement spike-ffi
- Fuzz A extension between interpreter, asm and spike.

```sh
$ cd fuzz_spike_ffi
$ sh build.sh
$ cd ..

$ cargo +nightly fuzz run isa_a
```

2023-03-30 01:45 UTC, XuJiandong requested changes

2023-03-30 01:45 UTC, XuJiandong commented on fuzz_spike_ffi/build.sh
> +set -ex
Add `readme` about how to build fuzz_spike_ffi crate.

2023-03-30 02:36 UTC, xxuejie commented
IMHO it might be better to put `fuzz_spike_ffi` in `ckb-vm-test-suite`

2023-03-30 09:07 UTC, mohanson commented
I created a crate so that ckb-vm only needs to import it into dependency

source: https://github.com/nervosnetwork/ckb-vm-test-suite/tree/master/spike-sys
crates.io https://crates.io/crates/spike-sys

cc @XuJiandong @xxuejie

2023-03-30 09:27 UTC, XuJiandong submitted a review, later dismissed

2023-03-31 01:37 UTC, xxuejie commented on fuzz/Cargo.toml
> -name = "asm"
Why do we replace one with the other, instead of keeping both fuzzing targets? I thought they can work for different use cases.

2023-03-31 02:00 UTC, mohanson commented on fuzz/Cargo.toml
> -name = "asm"
I added it back to the fuzz targets. It tests the load_program function which I overlooked earlier.

2023-03-31 02:01 UTC, xxuejie approved these changes

2023-03-31 02:34 UTC, merged